name: Validate Documentation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Lint Markdown
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
        
      - name: Run markdownlint
        run: markdownlint **/*.md --config .markdownlint.json

  vale-prose:
    runs-on: ubuntu-latest
    name: Check Prose Quality
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '**/*.md'
          vale_flags: '--config=.vale.ini'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  link-checker:
    runs-on: ubuntu-latest
    name: Check Links
    steps:
      - uses: actions/checkout@v4
      
      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/workflows/link-check-config.json'

  spell-check:
    runs-on: ubuntu-latest
    name: Spell Check
    steps:
      - uses: actions/checkout@v4
      
      - name: Spell check
        uses: streetsidesoftware/cspell-action@v2
        with:
          config: '.cspell.json'
          files: '**/*.md'

  schema-syntax:
    runs-on: ubuntu-latest
    name: Validate Schema Syntax
    steps:
      - uses: actions/checkout@v4
      
      - name: Check JSON Schema Syntax
        run: |
          find schemas -name "*.json" -exec python -m json.tool {} /dev/null \;

  rfc-validation:
    runs-on: ubuntu-latest
    name: Validate RFCs
    steps:
      - uses: actions/checkout@v4
      
      - name: Check RFC format
        run: |
          for file in RFCs/RFC-*.md; do
            if [ "$file" != "RFCs/RFC-TEMPLATE.md" ]; then
              echo "Validating $file"
              # Check required sections
              grep -q "^# RFC-[0-9]" "$file" || (echo "Missing RFC header in $file" && exit 1)
              grep -q "^- Status:" "$file" || (echo "Missing Status in $file" && exit 1)
              grep -q "^## Summary" "$file" || (echo "Missing Summary in $file" && exit 1)
              grep -q "^## Motivation" "$file" || (echo "Missing Motivation in $file" && exit 1)
            fi
          done